name: geoffnathanson1.com
favicon: null
layout_spectrum: 0.8449843076523393
typography_spectrum: 0.08763396763242781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.22347922110930085
  lightness: 0.0974551544059068
  saturation: 0.9520423035137355
  rhythmicContrast: 0.3373107980005443
purpose: []
